name: CI/CD Pipeline(main2)

on:
  workflow_dispatch:  # Allows manual triggering

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.9

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t python-flask-app .

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: SSH into EC2 and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # Navigate to home directory
            cd ~

            # Ensure Docker is installed
            if ! command -v docker &> /dev/null; then
              echo "Docker is not installed. Installing..."
              sudo apt update
              sudo apt install -y docker.io
              sudo systemctl start docker
              sudo systemctl enable docker
              sudo usermod -aG docker $USER
            fi
            
            # Remove old container if it exists
            docker stop python-flask-app || true
            docker rm python-flask-app || true

            # Remove old image
            docker rmi python-flask-app || true

            # Pull latest code (if applicable)
            cd ~/python-flask-app || git clone https://github.com/riya-kochar19/python-project.git
            cd ~/python-flask-app
            git pull origin main

            # Build and run the container
            docker build -t python-flask-app .
            docker run -d --name python-flask-app python-flask-app
          
